### ISSUE TITLE
我建议为这个仓库选择一个合适的开原协议

### ISSUE THREAD

**Issue by ghost** [GuYan1024/SJA#3]
一个合适的开源协议可以促进程序的传播，社区的建设，保障自己的利益。我建议为这个仓库选择一个合适的开源协议。比如MIT和GPL就是很好的协议。MIT的限制很宽松，而GPL则规定了，你改编这个项目时，成果也必需开源并使用GPL作为开源协议。

**Comment by remyhuang03** [comment]
适用协议的问题您可以具体实施。要期末了，我可能比较少上线，寒假会作进一步的开发。

**Comment by ghost** [comment]
那好，我选，嗯...GPL协议了。如果没问题我就加进去了。
