### ISSUE TITLE
我的想法

### ISSUE THREAD

**Issue by sun-xx** [GuYan1024/SJA#5]
**孤言您好**。  
我阅读过了UI部分的源代码。  
贴图非常不错，您应该是想还原A营的**SJA分析器scratch**版的效果。  
但是如果使用原生的tkinter与canvas开发会比较麻烦。  
我有一个大胆的意见，使用**pygame游戏库**来进行开发这个部分，可能会有更好的效果。  
望批准。

**Comment by ghost** [comment]
这个想法不错，可是我不熟悉pygame，我需要一点时间来学习它，不过我会做的。如果你对于这个问题有自己的解决方案，可以提一个pull request。

**Comment by sun-xx** [comment]
孤言已经同意我是这个项目的UI开发者了，以后我会开发UI部分您可以专心开发内核

**Comment by ghost** [comment]
嗯嗯

**Comment by remyhuang03** [comment]
我也可能需要一点时间熟悉下pygame，另外界面不必完全像sc版那样，适应核心即可

**Comment by 2048-GIF** [comment]
用pygame开发的不错，如果能有切换特效就更好了（我是kada某位

**Comment by sun-xx** [comment]
请问你是？



在 2021-02-12 09:40:42，"2048-GIF" <notifications@github.com> 写道：

用pygame开发的不错，如果能有切换特效就更好了（我是kada某位

**Comment by remyhuang03** [comment]
SJA的GUI开发的重点在呈现对比结果上，而不在特效上，特换切换没有必要。

**Comment by sun-xx** [comment]
是的，之前有人建议我做特效切换，我拒绝了



在 2021-02-13 14:19:20，"GuYan1024" <notifications@github.com> 写道：

SJA的GUI开发的重点在呈现对比结果上，而不在特效上，特换切换没有必要。
